use_frameworks!

platform :ios, '9.0'

target 'DXImagePicker_Example' do
  pod 'DXImagePicker', :path => '../'

  # https://github.com/banchichen/TZImagePickerController
  pod 'TZImagePickerController', '~> 3.6.6'
  # https://github.com/TimOliver/TOCropViewController
  pod 'CropViewController', '~> 2.6.0'

  target 'DXImagePicker_Tests' do
    inherit! :search_paths

    
  end
end
